name: Build and Deploy to Netlify
on:
  push:
  pull_request:
jobs:
  automate-netlify-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Deploy to Netlify Prod'
        run: |
          npm --verion && node --version

          npm install --global yarn

          cd frontend && yarn install

          cd ../

          yarn add netlify-cli -D

          cat netlify.toml

          netlify deploy --build --prod --auth ${{secrets.NETLIFY_AUTH_TOKEN}} --site ${{secrets.NETLIFY_SITE_ID}}
