name: Build and Deploy to Netlify
on:
  push:
  pull_request:
jobs:
  automate-netlify-deploy:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout
       uses: actions/checkout@v3
     - name: 'Deploy to Netlify Prod'
       run: |
        npm --version && node --version

        cd frontend && npm install

        cd ../

        npm i -D netlify-cli

        cat netlify.toml

        netlify deploy --build --prod --auth ${{secrets.NETLIFY_AUTH_TOKEN}} --site ${{secrets.NETLIFY_SITE_ID}}
