name: Build and Deploy to Netlify
on:
  push:
  pull_request:
jobs:
  automate-netlify-deploy:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout
       uses: actions/checkout@v3
     - name: Deploy to Netlify
       uses: nwtgck/actions-netlify@v1.2
       with:
        publish-dir: './frontend'
        netlify-config-path: './netlify.toml'
        production-branch: master
        github-token: ${{ secrets.GITHUB_TOKEN }}
        deploy-message: "Deploy from GitHub Actions"
        enable-pull-request-comment: true
        enable-commit-comment: true
        overwrites-pull-request-comment: true
       env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
       timeout-minutes: 1
